[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "342cbe0a04158f6dcb03ca0079991a51a4248c02"

[[constraint]]
  name = "github.com/hashicorp/yamux"
  revision = "f5742cb6b85602e7fa834e9d5d91a7d7fa850824"

[[constraint]]
  name = "github.com/mdlayher/vsock"
  revision = "738c88d6e4cfd60e8124a5344fa10d205fd828b9"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "cc4307ab6643668ce5abc6b524e1764a54c32550"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "4e3b9264a330d094b0386c3703c5f379119711e8"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "f006c2ac4710855cf0f916dd6b77acf6b048dc6e"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "87b1dfb5b2fa649f52695dd9eae19abe404a4308"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "2cbcf73e3dcdaa63941d0ec4008e69c089434756"

[[constraint]]
  name = "golang.org/x/net"
  revision = "a8b9294777976932365dabb6640cf1468d95c70f"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "ac767d655b305d4e9612f5f6e33120b9176c4ad4"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "5a9f7b402fe85096d2e1d0383435ee1876e863d0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
